
const category =[
            "Technology",
            "Finance",
            "Healthcare",
            "Retail",
            "Manufacturing",
            "Energy",
            "Telecommunications",
            "Transportation",
            "Real Estate",
            "Hospitality",
            "Entertainment",
            "Education",
            "Agriculture",
            "Automotive",
            "Biotechnology",
            "Media",
            "Construction",
            "Pharmaceuticals",
            "Environmental Services",
            "Consulting",
            "Insurance",
            "Food and Beverage",
            "Fashion",
            "Legal Services",
            "Fitness and Wellness",
            "Travel",
            "E-commerce",
            "Human Resources",
            "Renewable Energy",
            "Social Services"
]

export default category        